/* created on 2024-10-05 20:17:57 */
GRAN_MODEL(HERTZ, TANGENTIAL_HISTORY, COHESION_SJKR, ROLLING_EPSD2, SURFACE_DEFAULT)
GRAN_MODEL(HERTZ, TANGENTIAL_HISTORY, COHESION_SJKR2, ROLLING_EPSD2, SURFACE_DEFAULT)
GRAN_MODEL(HERTZ, TANGENTIAL_NO_HISTORY, COHESION_SJKR, ROLLING_EPSD2, SURFACE_DEFAULT)
GRAN_MODEL(HERTZ, TANGENTIAL_NO_HISTORY, COHESION_SJKR2, ROLLING_EPSD2, SURFACE_DEFAULT)
